//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Administration_Project.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=\"C:\\USERS\\ROBIN\\DOCUMENTS\\VISU" +
            "AL STUDIO 2015\\PROJECTS\\WPFMETROTEST\\WPFMETROTEST\\SCHOOL DATABASE.MDF\";Integrate" +
            "d Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True")]
        public string C__USERS_ROBIN_DOCUMENTS_VISUAL_STUDIO_2015_PROJECTS_WPFMETROTEST_WPFMETROTEST_SCHOOL_DATABASE_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_ROBIN_DOCUMENTS_VISUAL_STUDIO_2015_PROJECTS_WPFMETROTEST_WPFMETROTEST_SC" +
                    "HOOL_DATABASE_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"C:\\Users\\ROBIN\\Documents\\Vis" +
            "ual Studio 2015\\Projects\\WpfMetroTest\\WpfMetroTest\\School Database.mdf\";Integrat" +
            "ed Security=True;Connect Timeout=30")]
        public string School_DatabaseConnectionString {
            get {
                return ((string)(this["School_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"|DataDirectory|\\School Datab" +
            "ase.mdf\";Integrated Security=True;Connect Timeout=30")]
        public string School_DatabaseConnectionString1 {
            get {
                return ((string)(this["School_DatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5BN9EJ4\\SQLEXPRESS;Initial Catalog=StudentDB;Integrated Secur" +
            "ity=True")]
        public string StudentDBConnectionString {
            get {
                return ((string)(this["StudentDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Al-Jabz\\SQLEXPRESS;Initial Catalog=StudentDB;Integrated Security=True" +
            "")]
        public string StudentDBConnectionString1 {
            get {
                return ((string)(this["StudentDBConnectionString1"]));
            }
        }
    }
}
