#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Administration_Project.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StudentDB")]
	public partial class DataClassesLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmission_Exam_Result(Admission_Exam_Result instance);
    partial void UpdateAdmission_Exam_Result(Admission_Exam_Result instance);
    partial void DeleteAdmission_Exam_Result(Admission_Exam_Result instance);
    partial void InsertAdmission_Student(Admission_Student instance);
    partial void UpdateAdmission_Student(Admission_Student instance);
    partial void DeleteAdmission_Student(Admission_Student instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertTeacher(Teacher instance);
    partial void UpdateTeacher(Teacher instance);
    partial void DeleteTeacher(Teacher instance);
    partial void InsertInventory(Inventory instance);
    partial void UpdateInventory(Inventory instance);
    partial void DeleteInventory(Inventory instance);
    #endregion
		
		public DataClassesLinqDataContext() : 
				base(global::School_Administration_Project.Properties.Settings.Default.StudentDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Admission_Exam_Result> Admission_Exam_Results
		{
			get
			{
				return this.GetTable<Admission_Exam_Result>();
			}
		}
		
		public System.Data.Linq.Table<Admission_Student> Admission_Students
		{
			get
			{
				return this.GetTable<Admission_Student>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<Teacher> Teachers
		{
			get
			{
				return this.GetTable<Teacher>();
			}
		}
		
		public System.Data.Linq.Table<Inventory> Inventories
		{
			get
			{
				return this.GetTable<Inventory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin
	{
		
		private string _Admin_ID;
		
		private string _Admin_Role;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Full_Name;
		
		private string _Gender;
		
		private string _Fathers_Name;
		
		private string _Mothers_Name;
		
		private string _Address;
		
		private string _Mobile;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _Blood_Group;
		
		private string _Country;
		
		private string _Religoin;
		
		private string _Recruited_Session;
		
		private string _Designation;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _Status_Time_From;
		
		private System.Nullable<System.DateTime> _Status_Time_To;
		
		private System.Nullable<System.DateTime> _Last_Login_Date;
		
		private string _Pasword;
		
		private System.Nullable<System.DateTime> _Joined_Date;
		
		private System.Nullable<System.DateTime> _Resigned_Date;
		
		public Admin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_ID
		{
			get
			{
				return this._Admin_ID;
			}
			set
			{
				if ((this._Admin_ID != value))
				{
					this._Admin_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Role", DbType="VarChar(50)")]
		public string Admin_Role
		{
			get
			{
				return this._Admin_Role;
			}
			set
			{
				if ((this._Admin_Role != value))
				{
					this._Admin_Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="VarChar(50)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="VarChar(50)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="VarChar(50)")]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fathers_Name", DbType="VarChar(50)")]
		public string Fathers_Name
		{
			get
			{
				return this._Fathers_Name;
			}
			set
			{
				if ((this._Fathers_Name != value))
				{
					this._Fathers_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mothers_Name", DbType="VarChar(50)")]
		public string Mothers_Name
		{
			get
			{
				return this._Mothers_Name;
			}
			set
			{
				if ((this._Mothers_Name != value))
				{
					this._Mothers_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blood_Group", DbType="VarChar(50)")]
		public string Blood_Group
		{
			get
			{
				return this._Blood_Group;
			}
			set
			{
				if ((this._Blood_Group != value))
				{
					this._Blood_Group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religoin", DbType="VarChar(50)")]
		public string Religoin
		{
			get
			{
				return this._Religoin;
			}
			set
			{
				if ((this._Religoin != value))
				{
					this._Religoin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recruited_Session", DbType="VarChar(50)")]
		public string Recruited_Session
		{
			get
			{
				return this._Recruited_Session;
			}
			set
			{
				if ((this._Recruited_Session != value))
				{
					this._Recruited_Session = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="VarChar(50)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this._Designation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Time_From", DbType="Date")]
		public System.Nullable<System.DateTime> Status_Time_From
		{
			get
			{
				return this._Status_Time_From;
			}
			set
			{
				if ((this._Status_Time_From != value))
				{
					this._Status_Time_From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Time_To", DbType="Date")]
		public System.Nullable<System.DateTime> Status_Time_To
		{
			get
			{
				return this._Status_Time_To;
			}
			set
			{
				if ((this._Status_Time_To != value))
				{
					this._Status_Time_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Login_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Last_Login_Date
		{
			get
			{
				return this._Last_Login_Date;
			}
			set
			{
				if ((this._Last_Login_Date != value))
				{
					this._Last_Login_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pasword", DbType="VarChar(50)")]
		public string Pasword
		{
			get
			{
				return this._Pasword;
			}
			set
			{
				if ((this._Pasword != value))
				{
					this._Pasword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Joined_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Joined_Date
		{
			get
			{
				return this._Joined_Date;
			}
			set
			{
				if ((this._Joined_Date != value))
				{
					this._Joined_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resigned_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Resigned_Date
		{
			get
			{
				return this._Resigned_Date;
			}
			set
			{
				if ((this._Resigned_Date != value))
				{
					this._Resigned_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admission_Exam_Result")]
	public partial class Admission_Exam_Result : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Admission_Exam_ID;
		
		private string _Admission_Student_ID;
		
		private string _Writtern_Exam_Mark;
		
		private string _Viva_Exam_Mark;
		
		private string _Written_Examiner_ID;
		
		private string _Viva_Examiner_ID;
		
		private EntityRef<Admission_Student> _Admission_Student;
		
		private EntityRef<Teacher> _Teacher;
		
		private EntityRef<Teacher> _Teacher1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdmission_Exam_IDChanging(string value);
    partial void OnAdmission_Exam_IDChanged();
    partial void OnAdmission_Student_IDChanging(string value);
    partial void OnAdmission_Student_IDChanged();
    partial void OnWrittern_Exam_MarkChanging(string value);
    partial void OnWrittern_Exam_MarkChanged();
    partial void OnViva_Exam_MarkChanging(string value);
    partial void OnViva_Exam_MarkChanged();
    partial void OnWritten_Examiner_IDChanging(string value);
    partial void OnWritten_Examiner_IDChanged();
    partial void OnViva_Examiner_IDChanging(string value);
    partial void OnViva_Examiner_IDChanged();
    #endregion
		
		public Admission_Exam_Result()
		{
			this._Admission_Student = default(EntityRef<Admission_Student>);
			this._Teacher = default(EntityRef<Teacher>);
			this._Teacher1 = default(EntityRef<Teacher>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admission_Exam_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Admission_Exam_ID
		{
			get
			{
				return this._Admission_Exam_ID;
			}
			set
			{
				if ((this._Admission_Exam_ID != value))
				{
					this.OnAdmission_Exam_IDChanging(value);
					this.SendPropertyChanging();
					this._Admission_Exam_ID = value;
					this.SendPropertyChanged("Admission_Exam_ID");
					this.OnAdmission_Exam_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admission_Student_ID", DbType="VarChar(50)")]
		public string Admission_Student_ID
		{
			get
			{
				return this._Admission_Student_ID;
			}
			set
			{
				if ((this._Admission_Student_ID != value))
				{
					if (this._Admission_Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdmission_Student_IDChanging(value);
					this.SendPropertyChanging();
					this._Admission_Student_ID = value;
					this.SendPropertyChanged("Admission_Student_ID");
					this.OnAdmission_Student_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Writtern_Exam_Mark", DbType="VarChar(50)")]
		public string Writtern_Exam_Mark
		{
			get
			{
				return this._Writtern_Exam_Mark;
			}
			set
			{
				if ((this._Writtern_Exam_Mark != value))
				{
					this.OnWrittern_Exam_MarkChanging(value);
					this.SendPropertyChanging();
					this._Writtern_Exam_Mark = value;
					this.SendPropertyChanged("Writtern_Exam_Mark");
					this.OnWrittern_Exam_MarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Viva_Exam_Mark", DbType="VarChar(50)")]
		public string Viva_Exam_Mark
		{
			get
			{
				return this._Viva_Exam_Mark;
			}
			set
			{
				if ((this._Viva_Exam_Mark != value))
				{
					this.OnViva_Exam_MarkChanging(value);
					this.SendPropertyChanging();
					this._Viva_Exam_Mark = value;
					this.SendPropertyChanged("Viva_Exam_Mark");
					this.OnViva_Exam_MarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Written_Examiner_ID", DbType="VarChar(50)")]
		public string Written_Examiner_ID
		{
			get
			{
				return this._Written_Examiner_ID;
			}
			set
			{
				if ((this._Written_Examiner_ID != value))
				{
					if (this._Teacher1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWritten_Examiner_IDChanging(value);
					this.SendPropertyChanging();
					this._Written_Examiner_ID = value;
					this.SendPropertyChanged("Written_Examiner_ID");
					this.OnWritten_Examiner_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Viva_Examiner_ID", DbType="VarChar(50)")]
		public string Viva_Examiner_ID
		{
			get
			{
				return this._Viva_Examiner_ID;
			}
			set
			{
				if ((this._Viva_Examiner_ID != value))
				{
					if (this._Teacher.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnViva_Examiner_IDChanging(value);
					this.SendPropertyChanging();
					this._Viva_Examiner_ID = value;
					this.SendPropertyChanged("Viva_Examiner_ID");
					this.OnViva_Examiner_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Admission_Student_Admission_Exam_Result", Storage="_Admission_Student", ThisKey="Admission_Student_ID", OtherKey="Admission_Student_ID", IsForeignKey=true)]
		public Admission_Student Admission_Student
		{
			get
			{
				return this._Admission_Student.Entity;
			}
			set
			{
				Admission_Student previousValue = this._Admission_Student.Entity;
				if (((previousValue != value) 
							|| (this._Admission_Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Admission_Student.Entity = null;
						previousValue.Admission_Exam_Results.Remove(this);
					}
					this._Admission_Student.Entity = value;
					if ((value != null))
					{
						value.Admission_Exam_Results.Add(this);
						this._Admission_Student_ID = value.Admission_Student_ID;
					}
					else
					{
						this._Admission_Student_ID = default(string);
					}
					this.SendPropertyChanged("Admission_Student");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Teacher_Admission_Exam_Result", Storage="_Teacher", ThisKey="Viva_Examiner_ID", OtherKey="Teacher_ID", IsForeignKey=true)]
		public Teacher Teacher
		{
			get
			{
				return this._Teacher.Entity;
			}
			set
			{
				Teacher previousValue = this._Teacher.Entity;
				if (((previousValue != value) 
							|| (this._Teacher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Teacher.Entity = null;
						previousValue.Admission_Exam_Results.Remove(this);
					}
					this._Teacher.Entity = value;
					if ((value != null))
					{
						value.Admission_Exam_Results.Add(this);
						this._Viva_Examiner_ID = value.Teacher_ID;
					}
					else
					{
						this._Viva_Examiner_ID = default(string);
					}
					this.SendPropertyChanged("Teacher");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Teacher_Admission_Exam_Result1", Storage="_Teacher1", ThisKey="Written_Examiner_ID", OtherKey="Teacher_ID", IsForeignKey=true)]
		public Teacher Teacher1
		{
			get
			{
				return this._Teacher1.Entity;
			}
			set
			{
				Teacher previousValue = this._Teacher1.Entity;
				if (((previousValue != value) 
							|| (this._Teacher1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Teacher1.Entity = null;
						previousValue.Admission_Exam_Results1.Remove(this);
					}
					this._Teacher1.Entity = value;
					if ((value != null))
					{
						value.Admission_Exam_Results1.Add(this);
						this._Written_Examiner_ID = value.Teacher_ID;
					}
					else
					{
						this._Written_Examiner_ID = default(string);
					}
					this.SendPropertyChanged("Teacher1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admission_Student")]
	public partial class Admission_Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Admission_Student_ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Full_Name;
		
		private string _Gender;
		
		private string _Fathers_Name;
		
		private string _Mothers_Name;
		
		private string _Address;
		
		private string _Mobile;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _Blood_Group;
		
		private string _Country;
		
		private string _Religion;
		
		private string _Admission_Session;
		
		private string _Current_School;
		
		private string _Current_Grade;
		
		private string _Interested_Grade;
		
		private string _Group;
		
		private System.Nullable<System.DateTime> _Registered_Date;
		
		private EntitySet<Admission_Exam_Result> _Admission_Exam_Results;
		
		private EntitySet<Student> _Students;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdmission_Student_IDChanging(string value);
    partial void OnAdmission_Student_IDChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnFull_NameChanging(string value);
    partial void OnFull_NameChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnFathers_NameChanging(string value);
    partial void OnFathers_NameChanged();
    partial void OnMothers_NameChanging(string value);
    partial void OnMothers_NameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnBlood_GroupChanging(string value);
    partial void OnBlood_GroupChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnReligionChanging(string value);
    partial void OnReligionChanged();
    partial void OnAdmission_SessionChanging(string value);
    partial void OnAdmission_SessionChanged();
    partial void OnCurrent_SchoolChanging(string value);
    partial void OnCurrent_SchoolChanged();
    partial void OnCurrent_GradeChanging(string value);
    partial void OnCurrent_GradeChanged();
    partial void OnInterested_GradeChanging(string value);
    partial void OnInterested_GradeChanged();
    partial void OnGroupChanging(string value);
    partial void OnGroupChanged();
    partial void OnRegistered_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegistered_DateChanged();
    #endregion
		
		public Admission_Student()
		{
			this._Admission_Exam_Results = new EntitySet<Admission_Exam_Result>(new Action<Admission_Exam_Result>(this.attach_Admission_Exam_Results), new Action<Admission_Exam_Result>(this.detach_Admission_Exam_Results));
			this._Students = new EntitySet<Student>(new Action<Student>(this.attach_Students), new Action<Student>(this.detach_Students));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admission_Student_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Admission_Student_ID
		{
			get
			{
				return this._Admission_Student_ID;
			}
			set
			{
				if ((this._Admission_Student_ID != value))
				{
					this.OnAdmission_Student_IDChanging(value);
					this.SendPropertyChanging();
					this._Admission_Student_ID = value;
					this.SendPropertyChanged("Admission_Student_ID");
					this.OnAdmission_Student_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="VarChar(50)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="VarChar(50)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="VarChar(50)")]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this.OnFull_NameChanging(value);
					this.SendPropertyChanging();
					this._Full_Name = value;
					this.SendPropertyChanged("Full_Name");
					this.OnFull_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fathers_Name", DbType="VarChar(50)")]
		public string Fathers_Name
		{
			get
			{
				return this._Fathers_Name;
			}
			set
			{
				if ((this._Fathers_Name != value))
				{
					this.OnFathers_NameChanging(value);
					this.SendPropertyChanging();
					this._Fathers_Name = value;
					this.SendPropertyChanged("Fathers_Name");
					this.OnFathers_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mothers_Name", DbType="VarChar(50)")]
		public string Mothers_Name
		{
			get
			{
				return this._Mothers_Name;
			}
			set
			{
				if ((this._Mothers_Name != value))
				{
					this.OnMothers_NameChanging(value);
					this.SendPropertyChanging();
					this._Mothers_Name = value;
					this.SendPropertyChanged("Mothers_Name");
					this.OnMothers_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blood_Group", DbType="VarChar(50)")]
		public string Blood_Group
		{
			get
			{
				return this._Blood_Group;
			}
			set
			{
				if ((this._Blood_Group != value))
				{
					this.OnBlood_GroupChanging(value);
					this.SendPropertyChanging();
					this._Blood_Group = value;
					this.SendPropertyChanged("Blood_Group");
					this.OnBlood_GroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="VarChar(50)")]
		public string Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this.OnReligionChanging(value);
					this.SendPropertyChanging();
					this._Religion = value;
					this.SendPropertyChanged("Religion");
					this.OnReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admission_Session", DbType="VarChar(50)")]
		public string Admission_Session
		{
			get
			{
				return this._Admission_Session;
			}
			set
			{
				if ((this._Admission_Session != value))
				{
					this.OnAdmission_SessionChanging(value);
					this.SendPropertyChanging();
					this._Admission_Session = value;
					this.SendPropertyChanged("Admission_Session");
					this.OnAdmission_SessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Current_School", DbType="VarChar(50)")]
		public string Current_School
		{
			get
			{
				return this._Current_School;
			}
			set
			{
				if ((this._Current_School != value))
				{
					this.OnCurrent_SchoolChanging(value);
					this.SendPropertyChanging();
					this._Current_School = value;
					this.SendPropertyChanged("Current_School");
					this.OnCurrent_SchoolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Current_Grade", DbType="VarChar(50)")]
		public string Current_Grade
		{
			get
			{
				return this._Current_Grade;
			}
			set
			{
				if ((this._Current_Grade != value))
				{
					this.OnCurrent_GradeChanging(value);
					this.SendPropertyChanging();
					this._Current_Grade = value;
					this.SendPropertyChanged("Current_Grade");
					this.OnCurrent_GradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interested_Grade", DbType="VarChar(50)")]
		public string Interested_Grade
		{
			get
			{
				return this._Interested_Grade;
			}
			set
			{
				if ((this._Interested_Grade != value))
				{
					this.OnInterested_GradeChanging(value);
					this.SendPropertyChanging();
					this._Interested_Grade = value;
					this.SendPropertyChanged("Interested_Grade");
					this.OnInterested_GradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="VarChar(50)")]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this.OnGroupChanging(value);
					this.SendPropertyChanging();
					this._Group = value;
					this.SendPropertyChanged("Group");
					this.OnGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registered_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registered_Date
		{
			get
			{
				return this._Registered_Date;
			}
			set
			{
				if ((this._Registered_Date != value))
				{
					this.OnRegistered_DateChanging(value);
					this.SendPropertyChanging();
					this._Registered_Date = value;
					this.SendPropertyChanged("Registered_Date");
					this.OnRegistered_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Admission_Student_Admission_Exam_Result", Storage="_Admission_Exam_Results", ThisKey="Admission_Student_ID", OtherKey="Admission_Student_ID")]
		public EntitySet<Admission_Exam_Result> Admission_Exam_Results
		{
			get
			{
				return this._Admission_Exam_Results;
			}
			set
			{
				this._Admission_Exam_Results.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Admission_Student_Student", Storage="_Students", ThisKey="Admission_Student_ID", OtherKey="Admissin_Student_ID")]
		public EntitySet<Student> Students
		{
			get
			{
				return this._Students;
			}
			set
			{
				this._Students.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Admission_Exam_Results(Admission_Exam_Result entity)
		{
			this.SendPropertyChanging();
			entity.Admission_Student = this;
		}
		
		private void detach_Admission_Exam_Results(Admission_Exam_Result entity)
		{
			this.SendPropertyChanging();
			entity.Admission_Student = null;
		}
		
		private void attach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.Admission_Student = this;
		}
		
		private void detach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.Admission_Student = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Student_ID;
		
		private string _Admissin_Student_ID;
		
		private string _Subject_ID;
		
		private string _Result_ID;
		
		private string _Student_Status;
		
		private EntityRef<Admission_Student> _Admission_Student;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudent_IDChanging(string value);
    partial void OnStudent_IDChanged();
    partial void OnAdmissin_Student_IDChanging(string value);
    partial void OnAdmissin_Student_IDChanged();
    partial void OnSubject_IDChanging(string value);
    partial void OnSubject_IDChanged();
    partial void OnResult_IDChanging(string value);
    partial void OnResult_IDChanged();
    partial void OnStudent_StatusChanging(string value);
    partial void OnStudent_StatusChanged();
    #endregion
		
		public Student()
		{
			this._Admission_Student = default(EntityRef<Admission_Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Student_ID
		{
			get
			{
				return this._Student_ID;
			}
			set
			{
				if ((this._Student_ID != value))
				{
					this.OnStudent_IDChanging(value);
					this.SendPropertyChanging();
					this._Student_ID = value;
					this.SendPropertyChanged("Student_ID");
					this.OnStudent_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admissin_Student_ID", DbType="VarChar(50)")]
		public string Admissin_Student_ID
		{
			get
			{
				return this._Admissin_Student_ID;
			}
			set
			{
				if ((this._Admissin_Student_ID != value))
				{
					if (this._Admission_Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdmissin_Student_IDChanging(value);
					this.SendPropertyChanging();
					this._Admissin_Student_ID = value;
					this.SendPropertyChanged("Admissin_Student_ID");
					this.OnAdmissin_Student_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject_ID", DbType="VarChar(50)")]
		public string Subject_ID
		{
			get
			{
				return this._Subject_ID;
			}
			set
			{
				if ((this._Subject_ID != value))
				{
					this.OnSubject_IDChanging(value);
					this.SendPropertyChanging();
					this._Subject_ID = value;
					this.SendPropertyChanged("Subject_ID");
					this.OnSubject_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result_ID", DbType="VarChar(50)")]
		public string Result_ID
		{
			get
			{
				return this._Result_ID;
			}
			set
			{
				if ((this._Result_ID != value))
				{
					this.OnResult_IDChanging(value);
					this.SendPropertyChanging();
					this._Result_ID = value;
					this.SendPropertyChanged("Result_ID");
					this.OnResult_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Status", DbType="VarChar(50)")]
		public string Student_Status
		{
			get
			{
				return this._Student_Status;
			}
			set
			{
				if ((this._Student_Status != value))
				{
					this.OnStudent_StatusChanging(value);
					this.SendPropertyChanging();
					this._Student_Status = value;
					this.SendPropertyChanged("Student_Status");
					this.OnStudent_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Admission_Student_Student", Storage="_Admission_Student", ThisKey="Admissin_Student_ID", OtherKey="Admission_Student_ID", IsForeignKey=true)]
		public Admission_Student Admission_Student
		{
			get
			{
				return this._Admission_Student.Entity;
			}
			set
			{
				Admission_Student previousValue = this._Admission_Student.Entity;
				if (((previousValue != value) 
							|| (this._Admission_Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Admission_Student.Entity = null;
						previousValue.Students.Remove(this);
					}
					this._Admission_Student.Entity = value;
					if ((value != null))
					{
						value.Students.Add(this);
						this._Admissin_Student_ID = value.Admission_Student_ID;
					}
					else
					{
						this._Admissin_Student_ID = default(string);
					}
					this.SendPropertyChanged("Admission_Student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teacher")]
	public partial class Teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Teacher_ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Full_Name;
		
		private string _Gender;
		
		private string _Fathers_Name;
		
		private string _Mothers_Name;
		
		private string _Address;
		
		private string _Mobile;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _Blood_Group;
		
		private string _Country;
		
		private string _Religoin;
		
		private string _Recruited_Session;
		
		private string _Group;
		
		private string _Designation;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _Status_Time_From;
		
		private System.Nullable<System.DateTime> _Status_Time_To;
		
		private System.Nullable<System.DateTime> _Last_Login_Date;
		
		private string _Pasword;
		
		private System.Nullable<System.DateTime> _Joined_Date;
		
		private System.Nullable<System.DateTime> _Resigned_Date;
		
		private string _Marital_Status;
		
		private EntitySet<Admission_Exam_Result> _Admission_Exam_Results;
		
		private EntitySet<Admission_Exam_Result> _Admission_Exam_Results1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeacher_IDChanging(string value);
    partial void OnTeacher_IDChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnFull_NameChanging(string value);
    partial void OnFull_NameChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnFathers_NameChanging(string value);
    partial void OnFathers_NameChanged();
    partial void OnMothers_NameChanging(string value);
    partial void OnMothers_NameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnBlood_GroupChanging(string value);
    partial void OnBlood_GroupChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnReligoinChanging(string value);
    partial void OnReligoinChanged();
    partial void OnRecruited_SessionChanging(string value);
    partial void OnRecruited_SessionChanged();
    partial void OnGroupChanging(string value);
    partial void OnGroupChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnStatus_Time_FromChanging(System.Nullable<System.DateTime> value);
    partial void OnStatus_Time_FromChanged();
    partial void OnStatus_Time_ToChanging(System.Nullable<System.DateTime> value);
    partial void OnStatus_Time_ToChanged();
    partial void OnLast_Login_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnLast_Login_DateChanged();
    partial void OnPaswordChanging(string value);
    partial void OnPaswordChanged();
    partial void OnJoined_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnJoined_DateChanged();
    partial void OnResigned_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnResigned_DateChanged();
    partial void OnMarital_StatusChanging(string value);
    partial void OnMarital_StatusChanged();
    #endregion
		
		public Teacher()
		{
			this._Admission_Exam_Results = new EntitySet<Admission_Exam_Result>(new Action<Admission_Exam_Result>(this.attach_Admission_Exam_Results), new Action<Admission_Exam_Result>(this.detach_Admission_Exam_Results));
			this._Admission_Exam_Results1 = new EntitySet<Admission_Exam_Result>(new Action<Admission_Exam_Result>(this.attach_Admission_Exam_Results1), new Action<Admission_Exam_Result>(this.detach_Admission_Exam_Results1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Teacher_ID
		{
			get
			{
				return this._Teacher_ID;
			}
			set
			{
				if ((this._Teacher_ID != value))
				{
					this.OnTeacher_IDChanging(value);
					this.SendPropertyChanging();
					this._Teacher_ID = value;
					this.SendPropertyChanged("Teacher_ID");
					this.OnTeacher_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="VarChar(50)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="VarChar(50)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="VarChar(50)")]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this.OnFull_NameChanging(value);
					this.SendPropertyChanging();
					this._Full_Name = value;
					this.SendPropertyChanged("Full_Name");
					this.OnFull_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fathers_Name", DbType="VarChar(50)")]
		public string Fathers_Name
		{
			get
			{
				return this._Fathers_Name;
			}
			set
			{
				if ((this._Fathers_Name != value))
				{
					this.OnFathers_NameChanging(value);
					this.SendPropertyChanging();
					this._Fathers_Name = value;
					this.SendPropertyChanged("Fathers_Name");
					this.OnFathers_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mothers_Name", DbType="VarChar(50)")]
		public string Mothers_Name
		{
			get
			{
				return this._Mothers_Name;
			}
			set
			{
				if ((this._Mothers_Name != value))
				{
					this.OnMothers_NameChanging(value);
					this.SendPropertyChanging();
					this._Mothers_Name = value;
					this.SendPropertyChanged("Mothers_Name");
					this.OnMothers_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blood_Group", DbType="VarChar(50)")]
		public string Blood_Group
		{
			get
			{
				return this._Blood_Group;
			}
			set
			{
				if ((this._Blood_Group != value))
				{
					this.OnBlood_GroupChanging(value);
					this.SendPropertyChanging();
					this._Blood_Group = value;
					this.SendPropertyChanged("Blood_Group");
					this.OnBlood_GroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religoin", DbType="VarChar(50)")]
		public string Religoin
		{
			get
			{
				return this._Religoin;
			}
			set
			{
				if ((this._Religoin != value))
				{
					this.OnReligoinChanging(value);
					this.SendPropertyChanging();
					this._Religoin = value;
					this.SendPropertyChanged("Religoin");
					this.OnReligoinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recruited_Session", DbType="VarChar(50)")]
		public string Recruited_Session
		{
			get
			{
				return this._Recruited_Session;
			}
			set
			{
				if ((this._Recruited_Session != value))
				{
					this.OnRecruited_SessionChanging(value);
					this.SendPropertyChanging();
					this._Recruited_Session = value;
					this.SendPropertyChanged("Recruited_Session");
					this.OnRecruited_SessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="VarChar(50)")]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this.OnGroupChanging(value);
					this.SendPropertyChanging();
					this._Group = value;
					this.SendPropertyChanged("Group");
					this.OnGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="VarChar(50)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Time_From", DbType="Date")]
		public System.Nullable<System.DateTime> Status_Time_From
		{
			get
			{
				return this._Status_Time_From;
			}
			set
			{
				if ((this._Status_Time_From != value))
				{
					this.OnStatus_Time_FromChanging(value);
					this.SendPropertyChanging();
					this._Status_Time_From = value;
					this.SendPropertyChanged("Status_Time_From");
					this.OnStatus_Time_FromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Time_To", DbType="Date")]
		public System.Nullable<System.DateTime> Status_Time_To
		{
			get
			{
				return this._Status_Time_To;
			}
			set
			{
				if ((this._Status_Time_To != value))
				{
					this.OnStatus_Time_ToChanging(value);
					this.SendPropertyChanging();
					this._Status_Time_To = value;
					this.SendPropertyChanged("Status_Time_To");
					this.OnStatus_Time_ToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Login_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Last_Login_Date
		{
			get
			{
				return this._Last_Login_Date;
			}
			set
			{
				if ((this._Last_Login_Date != value))
				{
					this.OnLast_Login_DateChanging(value);
					this.SendPropertyChanging();
					this._Last_Login_Date = value;
					this.SendPropertyChanged("Last_Login_Date");
					this.OnLast_Login_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pasword", DbType="VarChar(50)")]
		public string Pasword
		{
			get
			{
				return this._Pasword;
			}
			set
			{
				if ((this._Pasword != value))
				{
					this.OnPaswordChanging(value);
					this.SendPropertyChanging();
					this._Pasword = value;
					this.SendPropertyChanged("Pasword");
					this.OnPaswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Joined_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Joined_Date
		{
			get
			{
				return this._Joined_Date;
			}
			set
			{
				if ((this._Joined_Date != value))
				{
					this.OnJoined_DateChanging(value);
					this.SendPropertyChanging();
					this._Joined_Date = value;
					this.SendPropertyChanged("Joined_Date");
					this.OnJoined_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resigned_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Resigned_Date
		{
			get
			{
				return this._Resigned_Date;
			}
			set
			{
				if ((this._Resigned_Date != value))
				{
					this.OnResigned_DateChanging(value);
					this.SendPropertyChanging();
					this._Resigned_Date = value;
					this.SendPropertyChanged("Resigned_Date");
					this.OnResigned_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marital_Status", DbType="VarChar(50)")]
		public string Marital_Status
		{
			get
			{
				return this._Marital_Status;
			}
			set
			{
				if ((this._Marital_Status != value))
				{
					this.OnMarital_StatusChanging(value);
					this.SendPropertyChanging();
					this._Marital_Status = value;
					this.SendPropertyChanged("Marital_Status");
					this.OnMarital_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Teacher_Admission_Exam_Result", Storage="_Admission_Exam_Results", ThisKey="Teacher_ID", OtherKey="Viva_Examiner_ID")]
		public EntitySet<Admission_Exam_Result> Admission_Exam_Results
		{
			get
			{
				return this._Admission_Exam_Results;
			}
			set
			{
				this._Admission_Exam_Results.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Teacher_Admission_Exam_Result1", Storage="_Admission_Exam_Results1", ThisKey="Teacher_ID", OtherKey="Written_Examiner_ID")]
		public EntitySet<Admission_Exam_Result> Admission_Exam_Results1
		{
			get
			{
				return this._Admission_Exam_Results1;
			}
			set
			{
				this._Admission_Exam_Results1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Admission_Exam_Results(Admission_Exam_Result entity)
		{
			this.SendPropertyChanging();
			entity.Teacher = this;
		}
		
		private void detach_Admission_Exam_Results(Admission_Exam_Result entity)
		{
			this.SendPropertyChanging();
			entity.Teacher = null;
		}
		
		private void attach_Admission_Exam_Results1(Admission_Exam_Result entity)
		{
			this.SendPropertyChanging();
			entity.Teacher1 = this;
		}
		
		private void detach_Admission_Exam_Results1(Admission_Exam_Result entity)
		{
			this.SendPropertyChanging();
			entity.Teacher1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inventory")]
	public partial class Inventory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Inventory_ID;
		
		private string _Inventory_Name;
		
		private System.Nullable<int> _Count;
		
		private System.Nullable<System.DateTime> _Last_Added_Date;
		
		private System.Nullable<int> _Last_Added_Count;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInventory_IDChanging(string value);
    partial void OnInventory_IDChanged();
    partial void OnInventory_NameChanging(string value);
    partial void OnInventory_NameChanged();
    partial void OnCountChanging(System.Nullable<int> value);
    partial void OnCountChanged();
    partial void OnLast_Added_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnLast_Added_DateChanged();
    partial void OnLast_Added_CountChanging(System.Nullable<int> value);
    partial void OnLast_Added_CountChanged();
    #endregion
		
		public Inventory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Inventory_ID
		{
			get
			{
				return this._Inventory_ID;
			}
			set
			{
				if ((this._Inventory_ID != value))
				{
					this.OnInventory_IDChanging(value);
					this.SendPropertyChanging();
					this._Inventory_ID = value;
					this.SendPropertyChanged("Inventory_ID");
					this.OnInventory_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory_Name", DbType="VarChar(50)")]
		public string Inventory_Name
		{
			get
			{
				return this._Inventory_Name;
			}
			set
			{
				if ((this._Inventory_Name != value))
				{
					this.OnInventory_NameChanging(value);
					this.SendPropertyChanging();
					this._Inventory_Name = value;
					this.SendPropertyChanged("Inventory_Name");
					this.OnInventory_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", DbType="Int")]
		public System.Nullable<int> Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this.OnCountChanging(value);
					this.SendPropertyChanging();
					this._Count = value;
					this.SendPropertyChanged("Count");
					this.OnCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Added_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Last_Added_Date
		{
			get
			{
				return this._Last_Added_Date;
			}
			set
			{
				if ((this._Last_Added_Date != value))
				{
					this.OnLast_Added_DateChanging(value);
					this.SendPropertyChanging();
					this._Last_Added_Date = value;
					this.SendPropertyChanged("Last_Added_Date");
					this.OnLast_Added_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Added_Count", DbType="Int")]
		public System.Nullable<int> Last_Added_Count
		{
			get
			{
				return this._Last_Added_Count;
			}
			set
			{
				if ((this._Last_Added_Count != value))
				{
					this.OnLast_Added_CountChanging(value);
					this.SendPropertyChanging();
					this._Last_Added_Count = value;
					this.SendPropertyChanged("Last_Added_Count");
					this.OnLast_Added_CountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
